apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: openshift-pipelines
spec:
  params:
  - name: url
    type: string
  - name: revision
    type: string
    default: main
  workspaces:
  - name: output
  steps:
  - name: clone
    image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:latest
    env:
    - name: HOME
      value: /workspace
    script: |
      #!/usr/bin/env sh
      set -eu
      /ko-app/git-init \
        -url="$(params.url)" \
        -revision="$(params.revision)" \
        -path="$(workspaces.output.path)" \
        -sslVerify=false
      cd "$(workspaces.output.path)"
      git log --oneline -1
