apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr-listener
  namespace: openshift-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-pr
    interceptors:
    - ref:
        name: github
        kind: ClusterInterceptor
      params:
      - name: eventTypes
        value: [pull_request]
    bindings:
    - ref: github-pr-binding
    template:
      ref: github-pr-template
