apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.28
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        - --helper-pod-node-selector
        - node-role.kubernetes.io/worker=
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_MAP_NAME
          value: local-path-config
      volumes:
      - name: config-volume
        configMap:
          name: local-path-config
