apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: zone-dmz
  labels:
    iec62443.zone: zone-dmz
    iec62443.purdue-level: "3"
  annotations:
    iec62443.sr: "SR 7.8 Audit Log Storage Capacity"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 20Gi
