apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: zone-dmz
  labels:
    iec62443.zone: zone-dmz
    iec62443.purdue-level: "3"
  annotations:
    iec62443.sr: "SR 4.1 Information Confidentiality"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
