apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unlabeled-data
  namespace: zone-ot
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
